'use client';
import Link from'next/link';import{useId,useState,useEffect,useRef}from'react';import{ArrowRight,ArrowLeft,Check,Info,ShieldCheck,RotateCcw,Pause,Play,LifeBuoy,CheckCircle2,TriangleAlert,Download}from'lucide-react';import{Checkbox}from'@/components/ui/checkbox';import{Accordion,AccordionItem,AccordionTrigger,AccordionContent}from'@/components/ui/accordion';import{Select,SelectTrigger,SelectValue,SelectContent,SelectItem}from'@/components/ui/select';import{Stepper}from'./shell';import{usePortal}from'./provider';import{track}from'@/lib/gtview/analytics';
export function CheckRow({label,checked,onChange,detail,disabled=false}:{label:string;checked:boolean;onChange:(b:boolean)=>void;detail?:string;disabled?:boolean}){const id=useId();return <div className={'check-row '+(checked?'checked':'')}><Checkbox id={id} disabled={disabled} checked={checked} onCheckedChange={v=>onChange(v===true)}/><label htmlFor={id}>{label}{detail&&<small>{detail}</small>}</label>{checked&&<Check className="row-check" size={16} aria-hidden="true"/>}</div>}
export function Choice({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:{value:string;label:string}[]}){const id=useId();return <div className="field"><label htmlFor={id}>{label}</label><Select value={value} onValueChange={onChange}><SelectTrigger id={id}><SelectValue placeholder="Choose an option"/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></div>}
export function Notice({children,tone='info'}:{children:React.ReactNode;tone?:'info'|'warning'|'danger'|'success'}){return <div className={'notice '+tone}>{tone==='success'?<CheckCircle2/>:tone==='warning'||tone==='danger'?<TriangleAlert/>:<Info/>}<div>{children}</div></div>}
export function ApprovalNote(){return <Notice>Concept walkthrough. Bracketed details need approval. Use the exact instructions from your kit before physically installing anything. <Link href="/support?issue=content">Request approved guidance</Link>.</Notice>}
export function Guided({phase,title,description,children,eyebrow}:{phase:number;title:string;description:string;children:React.ReactNode;eyebrow?:string}){const{saved,ready}=usePortal();return <main id="main" className="guided-main"><div className="guided-breadcrumb"><Link href="/">Your invitation</Link><span>/</span><span>Installation guide</span><span className="saved-label">{ready?(saved?'✓ Saved on this browser':'Not saved yet'):'Loading saved progress…'}</span></div><div className="guided-layout"><Stepper current={phase}/><div className="guided-content"><div className="page-kicker"><span>{eyebrow||'Phase '+String(phase+1).padStart(2,'0')+' of 06'}</span><span><ShieldCheck size={15}/> Safely parked, always</span></div><div className="page-heading"><h1 tabIndex={-1}>{title}</h1><p>{description}</p></div>{children}</div></div></main>}
export function Page({title,description,eyebrow,children}:{title:string;description:string;eyebrow:string;children:React.ReactNode}){return <main id="main" className="standard-main"><div className="page-heading"><p className="eyebrow">{eyebrow}</p><h1 tabIndex={-1}>{title}</h1><p>{description}</p></div>{children}</main>}
export function Actions({back,next,onNext,disabled,label='Continue',reason}:{back?:string;next?:string;onNext?:()=>void;disabled?:boolean;label?:string;reason?:string}){const{save}=usePortal();return <div className="action-area">{disabled&&reason&&<p className="gate-reason" role="status">{reason}</p>}<div className="bottom-actions">{back?<Link className="back-link" href={back}><ArrowLeft size={17}/>Go back</Link>:<span/>}<button className="save-button" onClick={save}>Save and finish later</button>{disabled?<button className="btn primary" disabled>{label}<ArrowRight size={18}/></button>:onNext?<button className="btn primary" onClick={onNext}>{label}<ArrowRight size={18}/></button>:<Link className="btn primary" href={next||'/'}>{label}<ArrowRight size={18}/></Link>}</div></div>}
export function Accordions({items}:{items:string[][]}){return <Accordion type="single" collapsible className="faq-list">{items.map(([title,body],i)=><AccordionItem value={String(i)} key={title}><AccordionTrigger>{title}</AccordionTrigger><AccordionContent>{body}</AccordionContent></AccordionItem>)}</Accordion>}
export function HelpLink(){return <Link className="help-link" href="/support" onClick={()=>track('help_opened')}><LifeBuoy size={17}/>I need help<ArrowRight size={16}/></Link>}
export function MotionPlayer({frames,children,label}:{frames:string[];children?:React.ReactNode;label:string}){const[frame,setFrame]=useState(0);const[playing,setPlaying]=useState(false);const[visible,setVisible]=useState(false);const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const observer=new IntersectionObserver(([e])=>setVisible(e.isIntersecting));if(ref.current)observer.observe(ref.current);return()=>observer.disconnect()},[]);useEffect(()=>{if(!playing||!visible||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const timer=setInterval(()=>setFrame(v=>(v+1)%frames.length),1700);return()=>clearInterval(timer)},[playing,visible,frames.length]);return <div ref={ref} className="motion-player"><div className="visual-header"><span>{label}</span><span>Concept sequence</span></div><div className={'instruction-visual frame-'+frame}>{children||<div className="sequence-focus"><span className="sequence-index">0{frame+1}</span><h3>{frames[frame]}</h3></div>}</div><div className="motion-caption" aria-live="polite"><span className="caption-number">{frame+1}</span>{frames[frame]}</div><div className="player-controls"><button onClick={()=>{setPlaying(!playing)}} aria-pressed={playing}>{playing?<Pause size={15}/>:<Play size={15}/>} {playing?'Pause':'Play steps'}</button><div className="frame-buttons">{frames.map((_,i)=><button key={i} aria-label={'Show frame '+(i+1)} aria-pressed={i===frame} onClick={()=>{setFrame(i);setPlaying(false)}}>{i+1}</button>)}</div><button onClick={()=>{setFrame(0);setPlaying(true);track('animation_replayed')}}><RotateCcw size={15}/>Show me again</button></div><details className="transcript"><summary>Read all frames</summary><ol>{frames.map(s=><li key={s}>{s}</li>)}</ol></details></div>}
export function downloadText(name:string,content:string){const url=URL.createObjectURL(new Blob([content],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
