import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,stateSchema,isPreparationReady,isKitReady,isInstallationReady,isAlignmentReady,isConnectionReady,isReviewReady,resumePath} from '../lib/gtview/state.ts';
function readyState(){const s=structuredClone(initialState);s.invitation='current';s.vehicle='matches';for(let i=0;i<6;i++)s.checks['safe-'+i]=true;for(const x of ['device','mount','attachment','cable','clips','wipe','guide','card'])s.checks['kit-'+x]=true;for(let i=0;i<4;i++)s.checks['phone-stage-'+i]=true;for(let i=0;i<4;i++)s.checks['align-'+i]=true;s.alignment='confirmed';for(let i=0;i<7;i++)s.diagnostics[i]='confirmed';s.checks.attestation=true;return s}
test('new visitor cannot complete an installation',()=>assert.equal(isReviewReady(initialState),false));
test('legacy device confirmations do not silently confirm phone installation',()=>{const s=structuredClone(initialState);for(let i=0;i<9;i++)s.checks['install-'+i]=true;assert.equal(isInstallationReady(s),false)});
test('older saved progress gains a stage default without losing existing checks',()=>{const s=structuredClone(initialState);delete s.phoneInstallStage;s.checks['safe-0']=true;const restored=stateSchema.parse(s);assert.equal(restored.phoneInstallStage,0);assert.equal(restored.checks['safe-0'],true);assert.equal(stateSchema.safeParse({...s,phoneInstallStage:4}).success,false)});
test('expired invitation and mismatched vehicle block readiness despite checked safety boxes',()=>{const s=readyState();s.invitation='expired';assert.equal(isPreparationReady(s),false);s.invitation='current';s.vehicle='vehicle';assert.equal(isReviewReady(s),false)});
test('each phase independently blocks final confirmation if incomplete',()=>{for(const edit of [s=>delete s.checks['safe-0'],s=>delete s.checks['kit-device'],s=>delete s.checks['phone-stage-1'],s=>delete s.checks['align-2'],s=>s.diagnostics[6]='attention',s=>s.checks.attestation=false]){const s=readyState();edit(s);assert.equal(isReviewReady(s),false)}});
test('uncertain alignment never passes',()=>{const s=readyState();s.alignment='uncertain';assert.equal(isAlignmentReady(s),false);assert.equal(isReviewReady(s),false)});
test('completed state survives the actual JSON storage boundary',()=>{const s=readyState();s.phoneInstallStage=2;s.lastPath='/install';const restored=stateSchema.parse(JSON.parse(JSON.stringify(s)));assert.equal(isReviewReady(restored),true);assert.equal(restored.phoneInstallStage,2);assert.equal(resumePath(restored),'/install')});
test('malformed stored types and invalid substeps are rejected',()=>{assert.equal(stateSchema.safeParse({...initialState,installStep:99}).success,false);assert.equal(stateSchema.safeParse({...initialState,checks:{attestation:'true'}}).success,false);assert.equal(stateSchema.safeParse({version:9}).success,false)});
test('resume cannot navigate to an external or arbitrary stored URL',()=>{assert.equal(resumePath({...initialState,lastPath:'https://example.com'}),'/before-you-start');assert.equal(resumePath({...initialState,lastPath:'/support'}),'/before-you-start')});
