'use client';
import {useState} from 'react';
import {CheckCircle2,TriangleAlert,RotateCcw} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
export function MountLab(){
 const [tilt,setTilt]=useState(0);const [example,setExample]=useState('clear');
 const good=tilt===0&&example==='clear';
 return <div className="mount-lab"><div className="lab-heading"><div><p className="eyebrow">LEARN BY TRYING</p><h3>A clear view, at a glance.</h3></div><span className="lab-label">Illustrative preview · no camera access</span></div>
 <Tabs value={example} onValueChange={value=>{setExample(value);setTilt(value==='tilted'?10:0)}}><TabsList aria-label="Road view examples" className="lab-tabs"><TabsTrigger value="clear">Clear view</TabsTrigger><TabsTrigger value="tilted">Tilted</TabsTrigger><TabsTrigger value="blocked">Blocked</TabsTrigger><TabsTrigger value="loose">Loose mount</TabsTrigger></TabsList></Tabs>
 <div className="lab-grid"><div className="lab-screen"><svg viewBox="0 0 600 300" role="img" aria-label={'Illustrative road view: '+(tilt?'tilted horizon':example==='blocked'?'obstructed view':'level horizon')+'. Mount stability cannot be determined from this view.'}><defs><clipPath id="road-clip"><rect width="600" height="300" rx="18"/></clipPath></defs><g clipPath="url(#road-clip)"><g transform={'rotate('+tilt+' 300 150)'}><rect x="-100" y="-150" width="800" height="650" fill="#dae9ef"/><rect x="-100" y="150" width="800" height="350" fill="#d4dfd1"/><path d="M265 150h70l230 220H35z" fill="#69727d"/><path d="M300 155v9m0 15v18m0 24v32m0 25v40" stroke="white" strokeWidth="5"/></g>{example==='blocked'&&<rect x="0" y="170" width="600" height="130" rx="28" fill="#25212c"/>}<path d="M30 150h540" stroke="#9145d7" strokeWidth="2" strokeDasharray="7 7"/><path d="M300 35v230" stroke="white" strokeOpacity=".6" strokeDasharray="5 6"/></g></svg><span>Sample camera view</span></div><div className={'lab-feedback '+(good?'is-good':'needs-fix')}><div>{good?<CheckCircle2/>:<TriangleAlert/>}<h4>{good?'Good view example':example==='loose'?'A clear view can still be loose':example==='blocked'?'The road is obscured':'The horizon is tilted'}</h4></div><p>{good?'The horizon is level and the road is visible. Your actual setup also needs the approved stability and alignment checks.':example==='loose'?'A preview cannot prove stability. Check the holder and phone using your kit’s method. Stop if either moves.':example==='blocked'?'Move the obstruction or adjust the approved placement. Keep the rear camera clear of the holder, dashboard and cable.':'Adjust the holder using the official alignment guide. Do not use this example as a numeric angle limit.'}</p><a href="/alignment-check">Check my actual setup →</a></div></div>
 <div className="lab-slider"><label id="tilt-label">Try changing the horizon <strong>{tilt===0?'Level example':'Tilted example'}</strong></label><Slider aria-labelledby="tilt-label" value={[tilt]} min={-15} max={15} step={1} onValueChange={v=>setTilt(v[0])}/><button onClick={()=>{setTilt(0);setExample('clear')}}><RotateCcw size={16}/>Reset example</button></div>
 </div>
}
