'use client';import{useEffect,useState}from'react';import Link from'next/link';import{useRouter}from'next/navigation';import{CheckCircle2,ArrowUpRight,ArrowRight,Circle,Camera,ListChecks}from'lucide-react';import{usePortal}from'./provider';import{Guided,Actions,CheckRow,Notice,TaskProgress}from'./ui';import{PhotoCard}from'./photo';import{reviewCards,photoTypes,phases}from'@/lib/gtview/content';import{isReviewReady,isConnectionReady,isAlignmentReady,reviewBlockers}from'@/lib/gtview/state';import{countPhotos}from'@/lib/gtview/photos';import{track}from'@/lib/gtview/analytics';
export default function Review(){const{state,check,patch,saved}=usePortal();const router=useRouter();
const statuses=[!!state.checks['phone-stage-0'],!!state.checks['phone-stage-1'],!!state.checks['align-2'],isAlignmentReady(state),!!state.checks['phone-stage-3'],isConnectionReady(state)];
const[photos,setPhotos]=useState(0);const[open,setOpen]=useState(false);
useEffect(()=>{let active=true;countPhotos('review-').then(n=>{if(active&&n>0){setPhotos(n);setOpen(true)}}).catch(()=>{});return()=>{active=false}},[]);
const blockers=reviewBlockers(state);const ready=blockers.length===0;const attested=!!state.checks.attestation;const next=blockers.length?phases[blockers[0]]:null;
return <Guided phase={5} title="Take one final look." description="Check the details that matter. You can open any step to make a correction.">
<section className={'readiness '+(ready?(attested?'done':'near'):'')} aria-labelledby="readiness-title"><div className="readiness-head"><ListChecks size={22} aria-hidden="true"/><div><h2 id="readiness-title">{ready?attested?'You’re ready to finish.':'Everything is checked. One box left.':'You have '+blockers.length+' step'+(blockers.length>1?'s':'')+' left.'}</h2><p>{ready?attested?'Save your local confirmation below. It stays on this browser.':'Tick the confirmation below, then save your record.':'Open a step to finish it. Nothing is lost — your answers are kept on this browser.'}</p></div></div><TaskProgress done={5-blockers.length} total={5} label="phases ready"/>
{blockers.length>0&&<ul className="readiness-list">{blockers.map(i=><li key={phases[i].href}><Link href={phases[i].href}><Circle size={16} aria-hidden="true"/><strong>{phases[i].label}</strong><span>Finish this step<ArrowRight size={15}/></span></Link></li>)}</ul>}</section>
<h2 className="review-subhead">Your six installation checks</h2>
<div className="review-grid">{reviewCards.map((c,i)=><Link className={'review-card '+(statuses[i]?'complete':'')} href={c.href} key={c.title}><span>{statuses[i]?<CheckCircle2/>:<Circle/>}</span><h3>{c.title}</h3><small>{statuses[i]?'Manually confirmed':'Open to finish'}<ArrowUpRight size={15}/></small></Link>)}</div>
<CheckRow label="I installed the device while safely parked and followed the approved GTview instructions." checked={attested} onChange={b=>check('attestation',b)}/>
<Notice>This concept saves a local confirmation only. There is no submission endpoint, official review, activation, or reward verification. Use your invitation’s official process to submit.</Notice>
<details className="optional-block" open={open} onToggle={e=>{const o=e.currentTarget.open;setOpen(o);if(!o)countPhotos('review-').then(setPhotos).catch(()=>{})}}><summary><Camera size={18} aria-hidden="true"/><span><strong>{photos?'Your optional photos':'Add optional photos'}</strong><small>{photos?photos+' saved on this browser · not submitted':photoTypes.length+' suggested views · for your own record only · not submitted'}</small></span></summary>
<Notice>Avoid people, readable plates, addresses, and personal items. Photos are saved locally, may include original file metadata, and can be removed below. Clearing browser data removes them.</Notice>
<div className="photo-grid">{photoTypes.map(p=><PhotoCard key={p.id} id={'review-'+p.id} label={p.label} why={p.why}/>)}</div></details>
<Actions back="/connect-and-test" disabled={!isReviewReady(state)||!saved} reason={!saved?'Enable local storage and save your progress before creating a confirmation.':next?<>Finish <Link href={next.href}>{next.label}</Link> to unlock your confirmation.</>:'Tick the confirmation above to save your record.'} label="Save local confirmation" onNext={()=>{patch({receipt:{id:'LOCAL-GT-'+crypto.randomUUID().slice(0,8).toUpperCase(),time:new Date().toISOString()}});track('setup_completed',{mode:'local'});router.push('/complete')}}/></Guided>}
